site_name: EspoCRM Python Client
site_description: Modern, type-safe and comprehensive EspoCRM API client library for Python
site_url: https://espocrm-python-client.readthedocs.io
repo_url: https://github.com/espocrm/espocrm-python-client
repo_name: espocrm/espocrm-python-client
edit_uri: edit/main/docs/

theme:
  name: material
  language: en
  palette:
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
    - announce.dismiss
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye

nav:
  - Home: index.md
  - Getting Started:
    - Installation: installation.md
    - Quick Start: quickstart.md
    - Configuration: configuration.md
  - Authentication:
    - Overview: authentication.md
    - API Key: auth/api-key.md
    - Basic Auth: auth/basic.md
    - HMAC Auth: auth/hmac.md
  - API Reference:
    - CRUD Operations: crud.md
    - Relationships: relationships.md
    - Metadata: metadata.md
    - Stream: stream.md
    - Attachments: attachments.md
    - Logging: logging.md
  - Advanced Usage:
    - Search & Filtering: advanced/search.md
    - Error Handling: advanced/error-handling.md
    - Performance: advanced/performance.md
    - Async Support: advanced/async.md
  - Tools:
    - CLI Tool: cli.md
    - Utilities: utilities.md
  - Examples:
    - Basic Examples: examples/basic.md
    - Advanced Examples: examples/advanced.md
    - Integration Examples: examples/integration.md
  - Development:
    - Contributing: contributing.md
    - Testing: testing.md
    - Release Process: release-process.md
  - Changelog: changelog.md

plugins:
  - search:
      lang: en
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            docstring_section_style: table
            show_source: true
            show_root_heading: true
            show_root_toc_entry: false
            show_root_full_path: false
            show_object_full_path: false
            show_category_heading: true
            show_if_no_docstring: false
            inherited_members: true
            members_order: source
            separate_signature: true
            unwrap_annotated: true
            filters: ["!^_"]
            merge_init_into_class: true
            docstring_options:
              ignore_init_summary: true
            signature_crossrefs: true
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
  - minify:
      minify_html: true

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      title: On this page
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: espocrm
      repo: espocrm-python-client
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/espocrm/espocrm-python-client
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/espocrm-python-client/
    - icon: fontawesome/solid/globe
      link: https://www.espocrm.com/
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

copyright: >
  Copyright &copy; 2025 EspoCRM Python Client Team –
  <a href="#__consent">Change cookie settings</a>